In [1]:
import psycopg2
import pandas as pd

In [2]:
conn = psycopg2.connect(
   database="d65103c5a2kbgs", 
    user='u16ifm924gr2m8', 
    password='pe4029f0ba1fbaafd034f4dbf17f703bf9a5d6c8420f07719f5db4054c9d4da40', 
    host='c1gvrf2q90nbcq.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com', 
    port = '5432'
    
)
cursor = conn.cursor()

In [3]:
sql = '''SELECT * from modified_label'''
data = pd.read_sql_query(sql, conn)

/var/folders/f5/vn3dt39d3hl4z6fvrlqn3s300000gp/T/ipykernel_76085/913544206.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql_query(sql, conn)

In [4]:
len(data)

4364

In [23]:
xsum_data = data[data['origin'] == 'XSUM']
xsum_data[xsum_data['user_id'] == 'c']

,uuid,user_id,docid,source,summary,model,benchmark_dataset_name,origin,nonfactual_span,error_type,mistake_severity,inference_likelihood,inference_knowledge,inference_severity,attempt_number
478,6056d646-7849-4d86-aac0-9b4699992146,4vQZBQ,XSUM-34017556:llama70b-ul2,"Scotland''s workforce is ""caught in a cruel tr...",A report by Citizens Advice Scotland has found...,llama70b,genaudit,XSUM,NaN,NaN,NaN,NaN,NaN,NaN,1
479,aa83732f-b908-44d4-b291-5eda22136e80,4vQZBQ,XSUM-34017556:gpt4-ul2,"Scotland''s workforce is ""caught in a cruel tr...",Citizens Advice Scotland (CAS) says the countr...,gpt4,genaudit,XSUM,to gain,highlight-somewhat_mistake,NaN,likely,common,moderate_consequence,1
480,fe3b18f1-03ca-42a3-a565-edcb93093793,4vQZBQ,XSUM-34017556:gpt4-ul2,"Scotland''s workforce is ""caught in a cruel tr...",Citizens Advice Scotland (CAS) says the countr...,gpt4,genaudit,XSUM,presented to the charity,highlight-mistake,NaN,not_likely,common,moderate_consequence,1
481,bb01c712-cdf8-4e7d-b4de-dce0472e1d4b,4vQZBQ,XSUM-34017556:gpt4-ul2,"Scotland''s workforce is ""caught in a cruel tr...",Citizens Advice Scotland (CAS) says the countr...,gpt4,genaudit,XSUM,low,highlight-mistake,NaN,likely,common,low_consequence,1
482,6a9fdef3-cb81-4361-bf81-86966cde76f5,4vQZBQ,XSUM-34017556:gpt4-ul2,"Scotland''s workforce is ""caught in a cruel tr...",Citizens Advice Scotland (CAS) says the countr...,gpt4,genaudit,XSUM,"leading to a ""growing crisis"" in Scotland",highlight-somewhat_mistake,NaN,likely,common,moderate_consequence,1
503,8fef3ffe-0a04-4710-814b-c042f7a6e450,4vQZBQ,XSUM-12889429:gpt4-ul2,Mining giant rio tinto has lowered its minimum...,"Rio Tinto, the mining giant, has reduced its m...",gpt4,genaudit,XSUM,NaN,NaN,NaN,NaN,NaN,NaN,1
504,394beeb3-36e2-4219-8ab2-666172f01944,4vQZBQ,XSUM-12889429:llama70b-ul2,Mining giant rio tinto has lowered its minimum...,Rio Tinto has reduced its minimum acceptance t...,llama70b,genaudit,XSUM,NaN,NaN,NaN,NaN,NaN,NaN,1
505,c510e4a6-e001-45eb-9360-e22ed1b753af,4vQZBQ,XSUM-12889429:llama70b-ul2,Mining giant rio tinto has lowered its minimum...,Rio Tinto has reduced its minimum acceptance t...,llama70b,genaudit,XSUM,$,highlight-mistake,NaN,not_likely,common,low_consequence,1
510,74ff3235-cb12-4490-9873-8a630a1fcf37,4vQZBQ,XSUM-35441162:llama70b-ul2,Claims direct cross-border rail services could...,There have been concerns that direct cross-bor...,llama70b,genaudit,XSUM,harmful,highlight-inference,NaN,obvious,common,low_consequence,1
512,1f15ab88-c4ec-4177-a829-5ce8a5f7d9b1,4vQZBQ,XSUM-29928061:gpt4-ul2,One of the longest-held detainees at the us fa...,One of the longest-held detainees at Guantanam...,gpt4,genaudit,XSUM,NaN,NaN,NaN,NaN,NaN,NaN,1
513,48cccf49-e208-4e8d-a9f6-f82e1daa7f4d,4vQZBQ,XSUM-28345611:gpt4-ul2,When you think of a laboratory you wouldn''t u...,Shakespeare''s Globe in London uses its in-hou...,gpt4,genaudit,XSUM,historically accurate,highlight-mistake,NaN,likely,common,moderate_consequence,1
515,cf08f9a5-184d-446f-bc61-d5c22d8def9d,4vQZBQ,XSUM-28345611:gpt4-ul2,When you think of a laboratory you wouldn''t u...,Shakespeare''s Globe in London uses its in-hou...,gpt4,genaudit,XSUM,highlight the scholar,highlight-mistake,NaN,not_likely,common,low_consequence,1
522,acad05ff-072a-4d44-b505-cf934896b3a0,4vQZBQ,XSUM-35441162:gpt4-ul2,Claims direct cross-border rail services could...,"Wales'' transport minister, Edwina Hart, has d...",gpt4,genaudit,XSUM,over the issue,highlight-somewhat_mistake,NaN,likely,common,moderate_consequence,1
526,f9386345-8b67-4ae5-af73-6b20371a2e34,4vQZBQ,XSUM-39664212:falcon7b-ul2,Police in germany have charged a man suspected...,A Russianman has been arrested for plotting a ...,falcon7b,genaudit,XSUM,debt and financial problems,highlight-somewhat_mistake,NaN,likely,somewhat_common,moderate_consequence,1
527,00fc4c35-e2f2-4f31-ba51-601b9e9eb6c0,4vQZBQ,XSUM-39664212:falcon7b-ul2,Police in germany have charged a man suspected...,A Russianman has been arrested for plotting a ...,falcon7b,genaudit,XSUM,Russian,highlight-inference,NaN,likely,common,low_consequence,1
528,2856eb5e-2209-46c4-82ce-d844f524f8c8,4vQZBQ,XSUM-39664212:falcon7b-ul2,Police in germany have charged a man suspected...,A Russianman has been arrested for plotting a ...,falcon7b,genaudit,XSUM,suspects,highlight-mistake,NaN,not_likely,common,moderate_consequence,1
529,efd4648d-327f-46e2-a34d-8e8074cbb6d9,4vQZBQ,XSUM-29928061:llama70b-ul2,One of the longest-held detainees at the us fa...,"Fawzi al-Odah, a Kuwaiti man who was held at G...",llama70b,genaudit,XSUM,NaN,NaN,NaN,NaN,NaN,NaN,1
530,e7615967-91ef-4785-bd51-935a86100cd0,4vQZBQ,XSUM-28345611:llama70b-ul2,When you think of a laboratory you wouldn''t u...,The Globe Theatre in London has a unique appro...,llama70b,genaudit,XSUM,academic rigor,highlight-somewhat_mistake,NaN,likely,common,moderate_consequence,1

In [6]:
data[data['docid'] == 'ACIBENCH-D2N092:mistral7b-ul2']

,uuid,user_id,docid,source,summary,model,benchmark_dataset_name,origin,nonfactual_span,error_type,mistake_severity,inference_likelihood,inference_knowledge,inference_severity,attempt_number
1961,b0f60d86-9582-4672-af1d-c33969a9a104,4vQZBQ,ACIBENCH-D2N092:mistral7b-ul2,"[doctor] hello , mrs .\nMartinez .\nGood to se...",The doctor and patient discussed the patient's...,mistral7b,genaudit,ACIBENCH,None,None,None,None,None,None,1
2155,0103a22d-518b-4d7c-b600-581bc85e17d7,g7wLBw,ACIBENCH-D2N092:mistral7b-ul2,"[doctor] hello , mrs .\nMartinez .\nGood to se...",The doctor and patient discussed the patient's...,mistral7b,genaudit,ACIBENCH,None,None,None,None,None,None,1
2700,aaf2d042-56a1-420d-bd23-b951ce64e44b,YtYC5w,ACIBENCH-D2N092:mistral7b-ul2,"[doctor] hello , mrs .\nMartinez .\nGood to se...",The doctor and patient discussed the patient's...,mistral7b,genaudit,ACIBENCH,in the,highlight-inference,None,obvious,somewhat_common,moderate_consequence,1
2702,d838c1be-a0ba-4d62-bdda-4add7c3093d3,YtYC5w,ACIBENCH-D2N092:mistral7b-ul2,"[doctor] hello , mrs .\nMartinez .\nGood to se...",The doctor and patient discussed the patient's...,mistral7b,genaudit,ACIBENCH,", and",highlight-mistake,None,not_likely,common,high_consequence,1
3021,715b40ca-e6fc-4ee1-aa68-2918ccc3dc94,USzArg,ACIBENCH-D2N092:mistral7b-ul2,"[doctor] hello , mrs .\nMartinez .\nGood to se...",The doctor and patient discussed the patient's...,mistral7b,genaudit,ACIBENCH,the pain,highlight-inference,None,obvious,common,low_consequence,1

In [7]:
# data_genaudit = data[data['benchmark_dataset_name'] == 'genaudit']

shortlisted_annotators = ['g7wLBw', 'YtYC5w', '4vQZBQ', 'USzArg']

In [8]:
data_all = data[data['user_id'].isin(shortlisted_annotators)]
len(data_all)

4364

In [9]:
data_all.to_csv('/Users/ramprasad.sa/hallucinations_annotations_trial/annotated_data/database_dump_hallu_trial_Mar_7_2025.csv')

In [10]:
data

,uuid,user_id,docid,source,summary,model,benchmark_dataset_name,origin,nonfactual_span,error_type,mistake_severity,inference_likelihood,inference_knowledge,inference_severity,attempt_number
0,56d81429-97f5-4dac-8eec-aed5f430d506,4vQZBQ,LLM-AggreFact:DqeLab1jnlXl51TV6g3fEIphiWL9btS0...,"Title: late rally for doc adams, a jeter befor...","""The New York Times"" published an article on A...",unknown,Wice,Wice,NaN,NaN,NaN,NaN,NaN,NaN,1
1,a5b223ca-7006-406a-96b7-900447c71fc4,USzArg,LLM-AggreFact:qw1pBWz5ynI76U121ehgtFXQXzIGP5lw...,Speaker 1: motion carries.\nSpeaker 0: thank y...,The document discusses the importance of oppos...,unknown,TofuEval-MeetB,TofuEval-MeetB,aims to repeal gas and vehicle taxes that fund...,highlight-inference,NaN,obvious,common,low_consequence,1
2,8742b6b1-a92e-4aec-920d-673e779ddc8c,USzArg,LLM-AggreFact:q56mHW6cfwgyKnrPD79U1HaTv2YaBZuP...,If there''s one thing that hurts more than the...,He can now continue his journey to his final d...,unknown,RAGTruth,RAGTruth,NaN,NaN,NaN,NaN,NaN,NaN,1
3,91786a5f-f376-41e9-8e93-038c9ef8fb74,YtYC5w,LLM-AggreFact:Q93Y9kC2QHHtQbdTNTouc7bXcTFWJCzp...,Title: theresa serber malkiel | jewish women''...,Her parents were Russian Jewish immigrants and...,unknown,Wice,Wice,Russian,highlight-inference,NaN,likely,common,moderate_consequence,1
4,3e847b65-9b87-41bf-b4ef-488a0271ebc4,USzArg,LLM-AggreFact:kvgYpbrK7d3F0wr6E4e9bznPh7DWgVBl...,We want our killers to be kind.\nTo walk into ...,"However, the NFL and the Patriots handled the ...",unknown,RAGTruth,RAGTruth,defend him as a good person,highlight-inference,NaN,obvious,common,low_consequence,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4359,292af26a-c061-4129-aab7-1672a7e986df,YtYC5w,XSUM-38021627:llama7b-ul2,In the scottish football association's stateme...,The Scottish Football Association (SFA) has an...,llama7b,genaudit,XSUM,widely acknowledged,highlight-inference,None,obvious,common,low_consequence,1
4360,b23962af-ef6c-4222-8667-8bdb4e389459,YtYC5w,XSUM-38021627:llama7b-ul2,In the scottish football association's stateme...,The Scottish Football Association (SFA) has an...,llama7b,genaudit,XSUM,optimistic,highlight-inference,None,not_likely,common,moderate_consequence,1
4361,f16887c8-647d-48ee-b650-7ae773ef25de,YtYC5w,XSUM-38021627:llama7b-ul2,In the scottish football association's stateme...,The Scottish Football Association (SFA) has an...,llama7b,genaudit,XSUM,three matches remaining,highlight-inference,None,not_likely,no,moderate_consequence,1
4362,6dc14a26-9833-4db0-94bf-b1b969ad3e3c,YtYC5w,XSUM-38021627:llama7b-ul2,In the scottish football association's stateme...,The Scottish Football Association (SFA) has an...,llama7b,genaudit,XSUM,continue to work with the players,highlight-inference,None,obvious,common,low_consequence,1
4363,b05a6095-1723-45bb-b1b8-ef274487b156,YtYC5w,XSUM-38021627:llama70b-ul2,In the scottish football association's stateme...,The Scottish Football Association (SFA) has de...,llama70b,genaudit,XSUM,unlikely that they would have the funds to do so,highlight-inference,None,likely,no,moderate_consequence,1

In [11]:
set(data['benchmark_dataset_name'])

{'ExpertQA',
 'RAGTruth',
 'TofuEval-MediaS',
 'TofuEval-MeetB',
 'Wice',
 'genaudit'}

In [15]:
data[data['benchmark_dataset_name'] == 'RAGTruth']

,uuid,user_id,docid,source,summary,model,benchmark_dataset_name,origin,nonfactual_span,error_type,mistake_severity,inference_likelihood,inference_knowledge,inference_severity,attempt_number
12,8742b6b1-a92e-4aec-920d-673e779ddc8c,USzArg,LLM-AggreFact:q56mHW6cfwgyKnrPD79U1HaTv2YaBZuP...,If there's one thing that hurts more than the ...,He can now continue his journey to his final d...,unknown,RAGTruth,RAGTruth,None,None,None,None,None,None,1
16,3e847b65-9b87-41bf-b4ef-488a0271ebc4,USzArg,LLM-AggreFact:kvgYpbrK7d3F0wr6E4e9bznPh7DWgVBl...,We want our killers to be kind.\nTo walk into ...,"However, the NFL and the Patriots handled the ...",unknown,RAGTruth,RAGTruth,defend him as a good person,highlight-inference,None,obvious,common,low_consequence,1
211,9791afb6-48ce-4b63-982d-06f67784f395,YtYC5w,LLM-AggreFact:OJ744memBaaVb3r0baDKcJIamfOfLLmb...,"{'name': ""holdren's grill"", 'address': '6920 m...",Customers are divided on their experiences.,unknown,RAGTruth,RAGTruth,None,None,None,None,None,None,1
237,89b6d30a-9b0b-4f9a-b305-604050e12c49,USzArg,LLM-AggreFact:IeuG3MIrisUMkxG1boz04DbOmJag4hMt...,"{'name': 'mediterra market and cafe', 'address...","While some appreciated the taste and quality, ...",unknown,RAGTruth,RAGTruth,appreciated the taste and quality,highlight-inference,None,obvious,common,low_consequence,1
243,080f013f-e5b6-448a-be29-89d5c8d4385f,USzArg,LLM-AggreFact:nuHdWGtmTsikmMG9EOkjGHPwvxgAw7yK...,Beer and ice cream.\nIt doesn't exactly spring...,Details of the campaign will be announced late...,unknown,RAGTruth,RAGTruth,set to release in the fall,highlight-inference,None,obvious,common,low_consequence,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1965,a59b2be3-5d8a-49c6-97a5-3144b6ab2bc0,USzArg,LLM-AggreFact:ZIccR5AbusKK0FSt8GeGNg5qYCsTJ5BJ...,{'question': 'what are the characteristics of ...,Diverse vegetation: The passages mention the p...,unknown,RAGTruth,RAGTruth,on the forest floor,highlight-inference,None,obvious,common,low_consequence,1
1966,8cc04448-7b87-4745-8b78-9d851bace9fa,USzArg,LLM-AggreFact:JpeVBwDCbcl7xbwj1G5COvAaRgCAsOdP...,"Norfolk, virginia (cnn)the second mate of the ...",His father had reported him missing on January...,unknown,RAGTruth,RAGTruth,None,None,None,None,None,None,1
1967,38aaa9b0-4ff7-499c-8121-6757d0947356,USzArg,LLM-AggreFact:Hf78rSEVQXUlwRVNpg1BO5QLWAcv6zue...,"{'name': ""dargan's irish pub & restaurant"", 'a...",With a rating of 4.0 stars and over 30 reviews...,unknown,RAGTruth,RAGTruth,over 30 reviews,highlight-inference,None,not_likely,somewhat_common,moderate_consequence,1
1968,d3ea7e23-e6df-48d1-90be-585b0798d7af,USzArg,LLM-AggreFact:Hf78rSEVQXUlwRVNpg1BO5QLWAcv6zue...,"{'name': ""dargan's irish pub & restaurant"", 'a...",With a rating of 4.0 stars and over 30 reviews...,unknown,RAGTruth,RAGTruth,a local favorite,highlight-inference,None,obvious,common,low_consequence,1
1969,5f272f42-5d38-4354-ad2b-db309dfb1d95,USzArg,LLM-AggreFact:Hf78rSEVQXUlwRVNpg1BO5QLWAcv6zue...,"{'name': ""dargan's irish pub & restaurant"", 'a...",With a rating of 4.0 stars and over 30 reviews...,unknown,RAGTruth,RAGTruth,"offering a welcoming atmosphere, delicious foo...",highlight-inference,None,obvious,common,low_consequence,1